---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex-sample-app
spec:
  selector:
    matchLabels:
      app: dex-sample-app
  replicas: 1
  template:
    metadata:
      labels:
        app: dex-sample-app
    spec:
      containers:
      - image: oukooveu/dex-sample-app:2.31.1
        imagePullPolicy: Always
        name: dex-sample-app
        ports:
        - containerPort: 5555
        args:
        - --issuer
        - "https://sso.example.com/dex"
        - --redirect-uri
        - "https://dex.example.com/callback"
        - --listen
        - "http://0.0.0.0:5555"
        - --debug
---
apiVersion: v1
kind: Service
metadata:
  name: dex-sample-app
spec:
  ports:
    - port: 80
      targetPort: 5555
      protocol: TCP
  selector:
    app: dex-sample-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dex-sample-app
spec:
  ingressClassName: nginx-internal
  rules:
    - host: dex.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dex-sample-app
                port:
                  number: 80
  tls:
  - hosts:
    - dex.example.com

